import type React from "react";

export const appSettings = {
  ahaPanel: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
  },
  ahaTabs: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "14px 20px 10px",
    borderBottom: "1px solid var(--border-dim)",
    overflowX: "auto" as const,
  },
  ahaTab: {
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap" as const,
    cursor: "pointer",
  },
  ahaBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto" as const,
    padding: "18px 20px 22px",
  },
  ahaContent: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 16,
  },
  ahaSection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 12,
    paddingBottom: 16,
    borderBottom: "1px solid var(--border-dim)",
  },
  ahaSectionHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  ahaSectionTitle: {
    fontSize: 13,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  ahaSectionDescription: {
    marginTop: 4,
    fontSize: 11.5,
    color: "var(--text-muted)",
    lineHeight: 1.5,
  },
  ahaGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 11,
  },
  ahaField: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 5,
  },
  ahaLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-secondary)",
  },
  ahaInput: {
    width: "100%",
    height: 34,
    padding: "0 10px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-primary)",
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  ahaHint: {
    fontSize: 11,
    color: "var(--text-hint)",
    lineHeight: 1.45,
  },
  ahaActionRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap" as const,
  },
  ahaGhostButton: {
    minHeight: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  ahaInlineButton: {
    height: 24,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "0 4px",
    border: "none",
    background: "transparent",
    color: "var(--accent)",
    fontSize: 11.5,
    fontWeight: 700,
    cursor: "pointer",
  },
  ahaFeedback: {
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.45,
  },
  ahaDropdown: {
    position: "absolute" as const,
    top: "100%",
    left: 0,
    right: 0,
    marginTop: 4,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
    maxHeight: 180,
    overflowY: "auto" as const,
    zIndex: 100,
    padding: 4,
  },
  ahaDropdownItem: {
    padding: "8px 12px",
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    cursor: "pointer",
    borderRadius: 4,
  },
  ahaToggleRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  ahaProvider: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 12,
    padding: "10px 0 12px",
    borderTop: "1px solid var(--border-dim)",
  },
  ahaProviderHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  ahaProviderTitleButton: {
    minWidth: 0,
    flex: 1,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    border: "none",
    background: "transparent",
    color: "var(--text-primary)",
    padding: 0,
    cursor: "pointer",
  },
  ahaProviderTitle: {
    flexShrink: 0,
    fontSize: 12.5,
    fontWeight: 750,
  },
  ahaProviderSummary: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
  },
  ahaProviderActions: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  ahaActiveBadge: {
    height: 24,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 8px",
    borderRadius: 999,
    border: "1px solid var(--accent)",
    background: "var(--accent-subtle)",
    color: "var(--accent)",
    fontSize: 11,
    fontWeight: 750,
    cursor: "pointer",
  },
  ahaInactiveBadge: {
    height: 24,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 8px",
    borderRadius: 999,
    border: "1px solid var(--border-medium)",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
  },
  ahaEmptyProvider: {
    padding: "12px 0",
    borderTop: "1px solid var(--border-dim)",
    color: "var(--text-hint)",
    fontSize: 12,
  },
  ahaDropdownToggle: {
    position: "absolute" as const,
    right: 1,
    top: 1,
    bottom: 1,
    width: 28,
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
  },
} satisfies Record<string, React.CSSProperties>;
