import type React from "react";

export const knowledge = {
  knowledgePane: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  knowledgeSidebar: {
    width: 300,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
  },
  knowledgeSidebarHeader: {
    padding: "18px 18px 14px",
    borderBottom: "1px solid var(--border-dim)",
  },
  knowledgeTitle: {
    fontSize: 15,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  knowledgeSubtitle: {
    marginTop: 5,
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.45,
  },
  knowledgeToolbar: {
    display: "flex",
    gap: 8,
    padding: "12px 14px",
    borderBottom: "1px solid var(--border-dim)",
  },
  knowledgeSmallBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 32,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  knowledgeList: {
    flex: 1,
    overflowY: "auto",
    padding: 10,
  },
  knowledgeCollectionItem: {
    width: "100%",
    padding: "10px 11px",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 5,
    borderRadius: 10,
    border: "1px solid transparent",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "var(--font-ui)",
  },
  knowledgeCollectionHeader: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  knowledgeCollectionName: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 700,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  knowledgeIconBtn: {
    width: 28,
    height: 28,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
  },
  knowledgeCollectionMeta: {
    fontSize: 11,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  knowledgeMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  knowledgeTopbar: {
    height: 58,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    padding: "0 18px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
    flexShrink: 0,
  },
  knowledgeTabs: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  knowledgeTab: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 34,
    padding: "0 11px",
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    fontSize: 12.5,
    fontWeight: 700,
  },
  knowledgeContent: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    overflow: "hidden",
  },
  knowledgePageList: {
    width: 280,
    flexShrink: 0,
    borderRight: "1px solid var(--border-dim)",
    overflowY: "auto",
    padding: 10,
    background: "var(--bg-subtle)",
  },
  knowledgePageItem: {
    width: "100%",
    padding: "9px 10px",
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "var(--font-ui)",
  },
  knowledgeEditorPane: {
    flex: 1,
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
    overflow: "hidden",
  },
  knowledgeEditorColumn: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    borderRight: "1px solid var(--border-dim)",
  },
  knowledgePreview: {
    minWidth: 0,
    overflowY: "auto",
    padding: 24,
    background: "var(--bg-panel)",
  },
  knowledgeForm: {
    flex: 1,
    overflowY: "auto",
    padding: 22,
    display: "flex",
    flexDirection: "column",
    gap: 18,
  },
  knowledgeField: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
  },
  knowledgeLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-secondary)",
  },
  knowledgeInput: {
    height: 36,
    border: "1px solid var(--border-medium)",
    borderRadius: 9,
    padding: "0 10px",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    outline: "none",
  },
  knowledgePanel: {
    flex: 1,
    overflowY: "auto",
    padding: 18,
  },
  knowledgeGraphShell: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    overflow: "hidden",
    background: "var(--bg-subtle)",
  },
  knowledgeGraphCanvasWrap: {
    position: "relative",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    background: "#101418",
    touchAction: "none",
    userSelect: "none",
  },
  knowledgeGraphHeader: {
    position: "absolute",
    zIndex: 4,
    top: 18,
    left: 18,
    right: 18,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    pointerEvents: "none",
  },
  knowledgeGraphTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "#f7fbff",
  },
  knowledgeGraphMeta: {
    marginTop: 4,
    fontSize: 12,
    color: "rgba(247, 251, 255, 0.62)",
  },
  knowledgeGraphCanvas: {
    position: "absolute",
    zIndex: 1,
    inset: 0,
  },
  knowledgeGraphLabel: {
    position: "absolute",
    zIndex: 6,
    left: 0,
    top: 0,
    maxWidth: 190,
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "5px 8px",
    borderRadius: 8,
    border: "1px solid rgba(255, 255, 255, 0.16)",
    backdropFilter: "blur(12px)",
    boxShadow: "0 10px 30px rgba(0, 0, 0, 0.22)",
    fontSize: 11.5,
    fontWeight: 700,
    cursor: "pointer",
    pointerEvents: "auto",
    transformOrigin: "0 0",
    transition: "opacity 0.12s ease, border-color 0.12s ease, background 0.12s ease",
  },
  knowledgeGraphLabelDot: {
    width: 7,
    height: 7,
    flexShrink: 0,
    borderRadius: 99,
    boxShadow: "0 0 12px currentColor",
  },
  knowledgeGraphLabelText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  knowledgeGraphDrawer: {
    width: 420,
    maxWidth: "42vw",
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderLeft: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
    boxShadow: "-18px 0 50px rgba(0, 0, 0, 0.18)",
  },
  knowledgeGraphDrawerHeader: {
    minHeight: 64,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    padding: "14px 14px 12px",
    borderBottom: "1px solid var(--border-dim)",
  },
  knowledgeGraphDrawerTitle: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 7,
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 800,
  },
  knowledgeGraphDrawerPath: {
    marginTop: 5,
    color: "var(--text-muted)",
    fontSize: 11.5,
    wordBreak: "break-all",
  },
  knowledgeGraphDrawerBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: 18,
  },
  knowledgeGraphDrawerState: {
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    color: "var(--text-muted)",
    fontSize: 13,
  },
  knowledgeGraphEmpty: {
    height: "100%",
    minHeight: 420,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    color: "var(--text-muted)",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-card)",
  },
  knowledgeGraphError: {
    position: "absolute",
    zIndex: 5,
    left: 18,
    bottom: 18,
    maxWidth: 520,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid rgba(220, 38, 38, 0.28)",
    background: "rgba(127, 29, 29, 0.92)",
    color: "#fee2e2",
    fontSize: 12,
    fontWeight: 700,
  },
  knowledgeCard: {
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-card)",
    padding: 14,
  },
  knowledgeDialogOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.34)",
  },
  knowledgeDialogBox: {
    width: 380,
    maxWidth: "calc(100vw - 48px)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: 18,
    borderRadius: 12,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-panel)",
    boxShadow: "0 22px 70px rgba(0, 0, 0, 0.32)",
  },
  knowledgeDialogHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
  },
  knowledgeDialogTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "var(--text-primary)",
  },
  knowledgeDialogSubtitle: {
    marginTop: 5,
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--text-muted)",
    wordBreak: "break-all",
  },
  knowledgeDialogFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
  },
} satisfies Record<string, React.CSSProperties>;
