import type React from "react";

export const knowledge = {
  knowledgePane: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  knowledgeSidebar: {
    width: 300,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
  },
  knowledgeSidebarHeader: {
    padding: "18px 18px 14px",
    borderBottom: "1px solid var(--border-dim)",
  },
  knowledgeTitle: {
    fontSize: 15,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  knowledgeSubtitle: {
    marginTop: 5,
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.45,
  },
  knowledgeToolbar: {
    display: "flex",
    gap: 8,
    padding: "12px 14px",
    borderBottom: "1px solid var(--border-dim)",
  },
  knowledgeSmallBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 32,
    padding: "0 10px",
    borderRadius: 8,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  knowledgeList: {
    flex: 1,
    overflowY: "auto",
    padding: 10,
  },
  knowledgeCollectionItem: {
    width: "100%",
    padding: "10px 11px",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 5,
    borderRadius: 10,
    border: "1px solid transparent",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "var(--font-ui)",
  },
  knowledgeCollectionHeader: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  knowledgeCollectionName: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 700,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  knowledgeIconBtn: {
    width: 28,
    height: 28,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
  },
  knowledgeCollectionMeta: {
    fontSize: 11,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  knowledgeMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  knowledgeTopbar: {
    height: 58,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    padding: "0 18px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
    flexShrink: 0,
  },
  knowledgeTabs: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  knowledgeTab: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    height: 34,
    padding: "0 11px",
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    fontSize: 12.5,
    fontWeight: 700,
  },
  knowledgeContent: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    overflow: "hidden",
  },
  knowledgePageList: {
    width: 280,
    flexShrink: 0,
    borderRight: "1px solid var(--border-dim)",
    overflowY: "auto",
    padding: 10,
    background: "var(--bg-subtle)",
  },
  knowledgePageItem: {
    width: "100%",
    padding: "9px 10px",
    borderRadius: 8,
    border: "1px solid transparent",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "var(--font-ui)",
  },
  knowledgeEditorPane: {
    flex: 1,
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
    overflow: "hidden",
  },
  knowledgeEditorColumn: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    borderRight: "1px solid var(--border-dim)",
  },
  knowledgePreview: {
    minWidth: 0,
    overflowY: "auto",
    padding: 24,
    background: "var(--bg-panel)",
  },
  knowledgeForm: {
    flex: 1,
    overflowY: "auto",
    padding: 22,
    display: "flex",
    flexDirection: "column",
    gap: 18,
  },
  knowledgeField: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
  },
  knowledgeLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-secondary)",
  },
  knowledgeInput: {
    height: 36,
    border: "1px solid var(--border-medium)",
    borderRadius: 9,
    padding: "0 10px",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontSize: 13,
    outline: "none",
  },
  knowledgePanel: {
    flex: 1,
    overflowY: "auto",
    padding: 18,
  },
  knowledgeCard: {
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-card)",
    padding: 14,
  },
  knowledgeDialogOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.34)",
  },
  knowledgeDialogBox: {
    width: 380,
    maxWidth: "calc(100vw - 48px)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: 18,
    borderRadius: 12,
    border: "1px solid var(--border-medium)",
    background: "var(--bg-panel)",
    boxShadow: "0 22px 70px rgba(0, 0, 0, 0.32)",
  },
  knowledgeDialogHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
  },
  knowledgeDialogTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "var(--text-primary)",
  },
  knowledgeDialogSubtitle: {
    marginTop: 5,
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--text-muted)",
    wordBreak: "break-all",
  },
  knowledgeDialogFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
  },
} satisfies Record<string, React.CSSProperties>;
