import type React from "react";

export const layout = {
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    background: "var(--bg-root)",
    overflow: "hidden",
  },
  welcomeBody: {
    height: "100%",
    display: "flex",
    overflow: "hidden",
    background: "var(--bg-shell)",
  },
  welcomeMain: { flex: 1, display: "flex", overflow: "hidden" },
  sidebar: {
    width: 220,
    flexShrink: 0,
    background: "linear-gradient(180deg, var(--bg-sidebar), var(--bg-sidebar-elevated))",
    borderRight: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column",
    padding: "18px 14px 14px",
  },
  sidebarBrand: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "2px 6px 18px",
    marginBottom: 14,
    borderBottom: "1px solid var(--border-dim)",
  },
  sidebarBrandIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    overflow: "hidden",
  },
  sidebarBrandBadge: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    borderRadius: 9,
    background: "rgba(9, 12, 18, 0.82)",
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: 800,
    letterSpacing: 0.6,
    paddingBottom: 4,
  },
  sidebarBrandTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "var(--text-primary)",
    lineHeight: 1.2,
  },
  sidebarBrandMeta: { marginTop: 3, fontSize: 12, color: "var(--text-muted)" },
  sidebarNav: { display: "flex", flexDirection: "column", gap: 6 },
  sidebarSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    padding: "0 10px 6px",
    textTransform: "uppercase" as const,
  },
  sidebarItem: {
    display: "flex",
    alignItems: "center",
    padding: "11px 12px",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 500,
    transition: "background 0.18s ease, color 0.18s ease",
    border: "1px solid transparent",
  },
  sidebarItemMeta: {
    marginLeft: "auto",
    minWidth: 22,
    height: 22,
    padding: "0 7px",
    borderRadius: 999,
    background: "rgba(123, 139, 166, 0.14)",
    color: "var(--text-muted)",
    fontSize: 11,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarFooter: {
    marginTop: "auto",
    paddingTop: 10,
    borderTop: "1px solid var(--border-dim)",
    display: "flex",
    justifyContent: "flex-start",
  },
  sidebarFooterActions: { display: "flex", alignItems: "center", gap: 4 },
  sidebarIconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    position: "relative",
    overflow: "visible",
    opacity: 0.5,
  },
  welcomePane: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  chatHomeBody: {
    flex: 1,
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  chatSessionPanel: {
    width: 260,
    flexShrink: 0,
    background: "var(--bg-sidebar)",
    borderRight: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  chatPanelIcon: {
    width: 22,
    height: 22,
    borderRadius: 7,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--accent-subtle)",
    color: "var(--accent)",
    flexShrink: 0,
  },
  chatNewSessionBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "none",
    border: "none",
    color: "var(--accent)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    padding: "4px 8px",
    borderRadius: 6,
  },
  chatMainPane: {
    flex: 1,
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  chatEmptyPane: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
  },
  categorySection: { display: "flex", flexDirection: "column", marginBottom: 2 },
  categoryHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 14px",
    cursor: "pointer",
    userSelect: "none",
    color: "var(--text-secondary)",
    fontSize: 12.5,
    fontWeight: 650,
    letterSpacing: 0.2,
    transition: "color 0.15s ease, background 0.15s ease",
  },
  categoryChevron: {
    flexShrink: 0,
    color: "var(--text-hint)",
    transition: "transform 0.18s ease",
  },
  categoryIcon: { flexShrink: 0, opacity: 0.85 },
  categoryName: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--text-secondary)",
  },
  categoryCount: {
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--text-hint)",
    padding: "1px 6px",
    borderRadius: 999,
    background: "var(--bg-subtle)",
    minWidth: 18,
    textAlign: "center",
    lineHeight: "14px",
  },
  categoryActionBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 2,
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    opacity: 0,
    transition: "opacity 0.15s ease",
    color: "var(--text-muted)",
  },
  categoryChildren: { display: "flex", flexDirection: "column", gap: 0, paddingLeft: 6 },
  categoryFooterRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "6px 10px",
    marginTop: "auto",
    borderTop: "1px solid var(--border-dim)",
  },
  categoryNewBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    background: "none",
    border: "none",
    color: "var(--text-muted)",
    fontSize: 12,
    cursor: "pointer",
    padding: "4px 6px",
    borderRadius: 5,
  },
  sessionCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "8px 12px 8px 20px",
    cursor: "pointer",
    borderRadius: 7,
    margin: "0 8px",
    transition: "background 0.15s ease",
  },
  sessionCardBody: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" },
  sessionCardTitle: {
    fontSize: 12.5,
    fontWeight: 550,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    lineHeight: 1.4,
  },
  sessionCardSub: {
    fontSize: 10.5,
    color: "var(--text-hint)",
    marginTop: 2,
  },
  sessionCardActions: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
  },
  sessionDragOver: {
    background: "var(--bg-hover)",
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: "var(--accent)",
    borderRadius: 7,
    margin: "0 8px",
  },
  searchRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "18px 22px 12px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
    flexShrink: 0,
  },
  searchBox: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
    padding: "12px 16px",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: 12,
    transition: "box-shadow 0.18s ease, border-color 0.18s ease",
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 500,
  },
  actionRow: { display: "flex", alignItems: "center", gap: 10, flexShrink: 0 },
  primaryActionBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    height: 38,
    padding: "0 16px",
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    fontSize: 13.5,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "var(--shadow-xs)",
  },
  projectSectionHeader: { padding: "14px 22px 6px", flexShrink: 0 },
  projectSectionTitle: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)" },
  projectSectionCaption: { marginTop: 4, fontSize: 12, color: "var(--text-muted)" },
  projectList: { flex: 1, overflowY: "auto", padding: "4px 22px 18px" },
  projectItem: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    width: "100%",
    minHeight: 72,
    padding: "12px 14px",
    border: "1px solid transparent",
    borderRadius: 14,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "var(--font-ui)",
    transition: "background 0.16s ease, border-color 0.16s ease",
  },
  projectName: {
    fontSize: 14,
    fontWeight: 650,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  projectMeta: {
    marginTop: 4,
    fontSize: 11.5,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  branchBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    color: "var(--text-secondary)",
    background: "var(--bg-subtle)",
    border: "1px solid var(--border-dim)",
    padding: "4px 8px",
    borderRadius: 999,
    flexShrink: 0,
  },
  projectTag: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    flexShrink: 0,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    padding: 32,
    textAlign: "center",
  },
  emptyOpenBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "10px 18px",
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    border: "1px solid var(--border-medium)",
    borderRadius: 12,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "var(--shadow-sm)",
  },
  projectBody: { flex: 1, display: "flex", overflow: "hidden" },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  placeholderView: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center" },
} satisfies Record<string, React.CSSProperties>;
