import type React from "react";

export const layout = {
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    background: "var(--bg-root)",
    overflow: "hidden",
  },
  welcomeBody: {
    height: "100%",
    display: "flex",
    overflow: "hidden",
    background: "var(--bg-shell)",
  },
  sidebar: {
    width: 220,
    flexShrink: 0,
    background: "linear-gradient(180deg, var(--bg-sidebar), var(--bg-sidebar-elevated))",
    borderRight: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column",
    padding: "18px 14px 14px",
  },
  sidebarBrand: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "2px 6px 18px",
    marginBottom: 14,
    borderBottom: "1px solid var(--border-dim)",
  },
  sidebarBrandIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    overflow: "hidden",
  },
  sidebarBrandTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "var(--text-primary)",
    lineHeight: 1.2,
  },
  sidebarBrandMeta: { marginTop: 3, fontSize: 12, color: "var(--text-muted)" },
  sidebarNav: { display: "flex", flexDirection: "column", gap: 6 },
  sidebarSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    padding: "0 10px 6px",
    textTransform: "uppercase" as const,
  },
  sidebarItemMeta: {
    marginLeft: "auto",
    minWidth: 22,
    height: 22,
    padding: "0 7px",
    borderRadius: 999,
    background: "rgba(123, 139, 166, 0.14)",
    color: "var(--text-muted)",
    fontSize: 11,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarFooter: {
    marginTop: "auto",
    paddingTop: 10,
    borderTop: "1px solid var(--border-dim)",
    display: "flex",
    justifyContent: "flex-start",
  },
  sidebarFooterActions: { display: "flex", alignItems: "center", gap: 4 },
  sidebarIconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    position: "relative",
    overflow: "visible",
    opacity: 0.5,
  },
  matchedKeywordsRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 4,
    marginTop: 4,
  },
  matchedKeywordTag: {
    fontSize: 10,
    padding: "1px 6px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
    border: "1px solid var(--border-dim)",
    lineHeight: "14px",
  },
  actionRow: { display: "flex", alignItems: "center", gap: 10, flexShrink: 0 },
  projectBody: { flex: 1, display: "flex", overflow: "hidden" },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
} satisfies Record<string, React.CSSProperties>;
