import type React from "react";

export const subAgent = {
  // ── Card Container ───────────────────────────────────────────────────────
  card: {
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    background: "var(--bg-subtle)",
    overflow: "hidden",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 12px",
    background: "transparent",
    border: "none",
    color: "var(--text-primary)",
    cursor: "pointer",
    textAlign: "left" as const,
  },
  cardBody: {
    padding: "0 12px 10px",
    fontSize: 11,
    lineHeight: 1.6,
    color: "var(--text-secondary)",
  },

  // ── Header Elements ──────────────────────────────────────────────────────
  headerName: {
    fontSize: 12,
    fontWeight: 700,
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  headerPhaseLabel: {
    fontSize: 11,
    fontWeight: 500,
    padding: "2px 8px",
    borderRadius: 10,
    background: "var(--bg-hover)",
    border: "1px solid var(--border-dim)",
    color: "var(--text-muted)",
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  headerPhaseLabelActive: {
    fontSize: 11,
    fontWeight: 500,
    padding: "2px 8px",
    borderRadius: 10,
    background: "color-mix(in srgb, var(--accent) 12%, transparent)",
    border: "1px solid color-mix(in srgb, var(--accent) 30%, transparent)",
    color: "var(--accent)",
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  headerElapsed: {
    fontSize: 11,
    color: "var(--text-muted)",
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
    marginLeft: 4,
  },

  // ── Phase Indicator ──────────────────────────────────────────────────────
  phaseBar: {
    display: "flex",
    alignItems: "center",
    gap: 0,
    marginBottom: 8,
    padding: "0 2px",
  },
  phaseStep: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    color: "var(--text-hint)",
    whiteSpace: "nowrap" as const,
  },
  phaseStepActive: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--accent)",
    whiteSpace: "nowrap" as const,
  },
  phaseStepDone: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    color: "var(--success, #22c55e)",
    whiteSpace: "nowrap" as const,
  },
  phaseStepFailed: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--danger, #ef4444)",
    whiteSpace: "nowrap" as const,
  },
  phaseConnector: {
    flex: 1,
    height: 1,
    background: "var(--border-dim)",
    margin: "0 6px",
    minWidth: 8,
  },
  phaseConnectorDone: {
    flex: 1,
    height: 1,
    background: "var(--success, #22c55e)",
    margin: "0 6px",
    minWidth: 8,
    opacity: 0.4,
  },

  // ── Stats Bar ────────────────────────────────────────────────────────────
  statsBar: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap" as const,
    marginBottom: 8,
  },
  statsChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    fontWeight: 500,
    padding: "2px 8px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    border: "1px solid var(--border-dim)",
    color: "var(--text-muted)",
  },

  // ── Tool Call Timeline ────────────────────────────────────────────────────
  timeline: {
    position: "relative" as const,
    paddingLeft: 16,
    maxHeight: 200,
    overflowY: "auto" as const,
    marginBottom: 6,
  },
  timelineItem: {
    position: "relative" as const,
    paddingBottom: 8,
  },
  timelineDot: {
    position: "absolute" as const,
    left: -16,
    top: 3,
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "var(--success, #22c55e)",
    border: "2px solid var(--bg-subtle)",
    boxSizing: "border-box" as const,
  },
  timelineDotRunning: {
    position: "absolute" as const,
    left: -16,
    top: 3,
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "var(--accent)",
    border: "2px solid var(--bg-subtle)",
    boxSizing: "border-box" as const,
  },
  timelineDotFailed: {
    position: "absolute" as const,
    left: -16,
    top: 3,
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "var(--danger, #ef4444)",
    border: "2px solid var(--bg-subtle)",
    boxSizing: "border-box" as const,
  },
  timelineLine: {
    position: "absolute" as const,
    left: -12,
    top: 11,
    width: 1,
    bottom: 0,
    background: "var(--border-dim)",
  },
  timelineToolName: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
  },
  timelineMeta: {
    fontSize: 10.5,
    color: "var(--text-muted)",
    marginTop: 1,
  },
  timelineResultPreview: {
    fontSize: 10.5,
    color: "var(--text-hint)",
    marginTop: 1,
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },

  // ── Task Description ─────────────────────────────────────────────────────
  taskDescription: {
    color: "var(--text-muted)",
    marginBottom: 6,
    fontSize: 11,
    lineHeight: 1.5,
  },

  // ── Result Block ─────────────────────────────────────────────────────────
  resultBlock: {
    margin: 0,
    padding: "8px 10px",
    borderRadius: 8,
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    color: "var(--text-primary)",
    fontSize: 11,
    lineHeight: 1.55,
    fontFamily: "var(--font-mono)",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
    maxHeight: 240,
    overflowY: "auto" as const,
  },
  resultLabel: {
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: 0.3,
    marginBottom: 4,
    textTransform: "uppercase" as const,
  },

  // ── Error Block ──────────────────────────────────────────────────────────
  errorBlock: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 8,
    background: "rgba(239, 68, 68, 0.08)",
    border: "1px solid rgba(239, 68, 68, 0.25)",
    color: "var(--danger, #ef4444)",
    fontSize: 11,
    lineHeight: 1.55,
    fontFamily: "var(--font-mono)",
    wordBreak: "break-word" as const,
  },
  errorLabel: {
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--danger, #ef4444)",
    letterSpacing: 0.3,
    marginBottom: 4,
    textTransform: "uppercase" as const,
  },

  // ── Progress Row ─────────────────────────────────────────────────────────
  progressRow: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
    maxHeight: 100,
    overflowY: "auto" as const,
    marginTop: 4,
  },
  progressItem: {
    padding: "1px 4px",
    fontFamily: "var(--font-mono)",
    fontSize: 10.5,
    color: "var(--text-muted)",
    wordBreak: "break-all" as const,
    whiteSpace: "pre-wrap" as const,
  },
} satisfies Record<string, React.CSSProperties>;
