import type React from "react";

export const task = {
  taskPanel: {
    width: 260,
    flexShrink: 0,
    background: "var(--bg-sidebar)",
    borderRight: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  panelHeader: {
    height: 48,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 10px 0 6px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  backBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 6px",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    color: "var(--text-muted)",
    flexShrink: 0,
  },
  panelProjectName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  panelSearchWrap: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    margin: "8px 10px 4px",
    padding: "6px 9px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
  },
  panelSearchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
  },
  taskActionsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "6px 19px 4px",
  },
  taskDivider: { height: 1, background: "var(--border-dim)", margin: "4px 10px 2px" },
  taskListScroll: {
    flex: 1,
    overflowY: "auto",
    padding: "2px 0 12px",
    overflowAnchor: "none" as const,
  },
  taskPanelFooter: {
    padding: "10px 10px",
    borderTop: "1px solid var(--border-dim)",
    display: "flex",
    justifyContent: "flex-start",
    background: "var(--bg-sidebar)",
  },
  taskListEmpty: {
    padding: "24px 16px",
    fontSize: 12,
    color: "var(--text-hint)",
    textAlign: "center",
  },
  taskCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 9,
    padding: "7px 12px",
    margin: "1px 6px",
    borderRadius: 6,
    cursor: "pointer",
    transition: "background 0.1s",
  },
  taskCardTitle: {
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  taskCardSub: { fontSize: 11, color: "var(--text-muted)", marginTop: 1 },
  taskCardActions: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
  },
  sessionRunningIcon: {
    color: "var(--accent)",
    flexShrink: 0,
  },
  taskDeleteBtn: {
    flexShrink: 0,
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-hint)",
    cursor: "pointer",
    transition: "opacity 0.12s ease, background 0.12s ease, color 0.12s ease",
  },
} satisfies Record<string, React.CSSProperties>;
