import type { AgentType } from "../../types";

export const DISPATCH_AGENT_META: Record<
  AgentType,
  { title: string; badge: string; hint: string }
> = {
  claude: {
    title: "Claude 子任务审查",
    badge: "Claude",
    hint: "Claude 更快，适合新功能、算法试验和问题探索。",
  },
  codex: {
    title: "Codex 子任务审查",
    badge: "Codex",
    hint: "Codex 更慢但更仔细，适合重构、结构整理和高风险修改。",
  },
};

// ── Styles ───────────────────────────────────────────────────────────────────

export const dispatcherChatStyles = {
  pythonRunnerShell: {
    display: "flex",
    flex: 1,
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  container: {
    display: "flex",
    flexDirection: "column" as const,
    flex: 1,
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    background:
      "radial-gradient(circle at 78% 0%, color-mix(in srgb, var(--accent) 12%, transparent), transparent 30%), linear-gradient(180deg, color-mix(in srgb, var(--chat-main-rail) 92%, transparent), transparent)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    borderBottom: "1px solid var(--chat-glass-border)",
    background: "color-mix(in srgb, var(--chat-surface) 86%, transparent)",
    backdropFilter: "blur(22px) saturate(1.12)",
    WebkitBackdropFilter: "blur(22px) saturate(1.12)",
    WebkitAppRegion: "drag" as const,
    flexShrink: 0,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  headerIcon: {
    width: 30,
    height: 30,
    borderRadius: 11,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background:
      "linear-gradient(135deg, color-mix(in srgb, var(--accent) 22%, var(--bg-card)), color-mix(in srgb, var(--warning) 14%, var(--bg-card)))",
    color: "var(--accent)",
    border: "1px solid color-mix(in srgb, var(--accent) 24%, var(--chat-glass-border))",
  },
  headerTitle: {
    fontSize: "14px",
    fontWeight: 850,
    letterSpacing: 0,
    color: "var(--text-primary)",
  },
  headerPlanBadge: {
    border: "1px solid color-mix(in srgb, var(--accent) 22%, var(--border-dim))",
    borderRadius: 999,
    padding: "3px 7px",
    color: "var(--accent)",
    background: "var(--accent-subtle)",
    fontSize: 10,
    fontWeight: 800,
  },
  thinkingDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: "var(--accent)",
    animation: "pulse 1.5s ease-in-out infinite",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    minWidth: 0,
    WebkitAppRegion: "no-drag" as const,
  },
  conversationSearchBox: {
    height: "30px",
    minWidth: "260px",
    maxWidth: "360px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "0 6px 0 9px",
    border: "1px solid color-mix(in srgb, var(--accent) 28%, var(--border-dim))",
    borderRadius: "999px",
    background: "color-mix(in srgb, var(--chat-surface-strong) 94%, transparent)",
    color: "var(--text-muted)",
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.08)",
    flexShrink: 1,
  },
  conversationSearchInput: {
    width: "min(150px, 22vw)",
    minWidth: "82px",
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: "12px",
    lineHeight: 1,
  },
  conversationSearchCount: {
    minWidth: "42px",
    color: "var(--text-hint)",
    fontSize: "11px",
    fontVariantNumeric: "tabular-nums" as const,
    textAlign: "right" as const,
    whiteSpace: "nowrap" as const,
  },
  conversationSearchNavBtn: (disabled: boolean) => ({
    width: "22px",
    height: "22px",
    border: "1px solid transparent",
    borderRadius: "999px",
    background: "transparent",
    color: disabled ? "var(--text-hint)" : "var(--text-secondary)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: disabled ? "not-allowed" : "pointer",
    padding: 0,
    flexShrink: 0,
    opacity: disabled ? 0.48 : 1,
  }),
  modeToggleBtn: (active: boolean) => ({
    height: "34px",
    padding: "0 11px",
    borderRadius: "999px",
    border: active
      ? "1px solid color-mix(in srgb, var(--accent) 48%, transparent)"
      : "1px solid var(--border-dim)",
    background: active
      ? "color-mix(in srgb, var(--accent) 14%, var(--chat-surface-strong))"
      : "color-mix(in srgb, var(--chat-surface-strong) 88%, transparent)",
    color: active ? "var(--accent)" : "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: active ? "0 12px 24px -18px var(--accent)" : "var(--shadow-xs)",
  }),
  headerBtn: {
    padding: "6px 10px",
    fontSize: "11px",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    background: "color-mix(in srgb, var(--chat-surface-strong) 84%, transparent)",
    border: "1px solid var(--chat-glass-border)",
    borderRadius: "999px",
    color: "var(--text-secondary)",
    cursor: "pointer",
  },
  headerSignal: {
    width: "8px",
    height: "8px",
    borderRadius: "999px",
    flexShrink: 0,
  },
  keywordsBar: {
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: "5px",
    padding: "7px 18px",
    borderBottom: "1px solid var(--chat-glass-border)",
    background: "color-mix(in srgb, var(--chat-surface) 58%, transparent)",
    WebkitAppRegion: "no-drag" as const,
    flexShrink: 0,
  },
  keywordTag: {
    display: "inline-flex",
    alignItems: "center",
    height: "20px",
    padding: "0 8px",
    fontSize: "11px",
    fontWeight: 600,
    lineHeight: "20px",
    borderRadius: "999px",
    border: "1px solid var(--border-dim)",
    background: "color-mix(in srgb, var(--bg-subtle) 80%, transparent)",
    color: "var(--text-secondary)",
    cursor: "pointer",
    userSelect: "none" as const,
    whiteSpace: "nowrap" as const,
    transition: "background 0.15s, border-color 0.15s",
  },
  headerBtnActive: {
    background: "var(--accent-subtle)",
    borderColor: "var(--accent)",
    color: "var(--accent)",
  },
  messageList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto" as const,
    overflowX: "hidden" as const,
    overflowAnchor: "none" as const,
    padding: "26px 22px 20px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
    alignItems: "stretch",
  },
  runErrorBanner: {
    border: "1px solid color-mix(in srgb, var(--danger) 36%, var(--border-primary))",
    background: "color-mix(in srgb, var(--danger) 10%, var(--bg-panel))",
    color: "var(--danger)",
    borderRadius: "8px",
    padding: "10px 12px",
    fontSize: "12px",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap" as const,
  },
  drawer: {
    border: "1px solid color-mix(in srgb, var(--accent) 18%, var(--chat-glass-border))",
    background: "var(--chat-surface)",
    borderRadius: 16,
    padding: "12px 14px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
    boxShadow: "var(--chat-shadow-soft)",
  },
  drawerHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    minWidth: 0,
  },
  drawerTitle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    color: "var(--text-primary)",
    fontSize: 12,
    fontWeight: 800,
  },
  drawerPath: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    color: "var(--text-hint)",
    fontSize: 11,
    fontFamily: "var(--font-mono)",
  },
  drawerQuestion: {
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 700,
    lineHeight: 1.5,
  },
  drawerSummary: {
    color: "var(--text-secondary)",
    fontSize: 12,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap" as const,
  },
  drawerOptionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 8,
  },
  drawerOptionBtn: {
    textAlign: "left" as const,
    border: "1px solid var(--border-dim)",
    background: "color-mix(in srgb, var(--bg-panel) 84%, transparent)",
    borderRadius: 10,
    padding: "10px 11px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 5,
    cursor: "pointer",
  },
  drawerOptionLabel: {
    color: "var(--text-primary)",
    fontSize: 12,
    fontWeight: 800,
  },
  drawerOptionDesc: {
    color: "var(--text-secondary)",
    fontSize: 11.5,
    lineHeight: 1.45,
  },
  drawerCustomBox: {
    border: "1px solid var(--border-dim)",
    borderRadius: 10,
    padding: 8,
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
    background: "color-mix(in srgb, var(--bg-panel) 84%, transparent)",
  },
  drawerCustomInput: {
    border: "none",
    outline: "none",
    resize: "vertical" as const,
    minHeight: 64,
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
    lineHeight: 1.5,
  },
  emptyLauncherWrap: (layoutMode: "single" | "split") => ({
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    width: "100%",
    minHeight: "100%",
    gap: layoutMode === "single" ? "22px" : "0",
    padding: layoutMode === "single" ? "44px 24px 56px" : "28px 12px 44px",
    boxSizing: "border-box" as const,
  }),
  emptyLauncherHero: (layoutMode: "single" | "split") => ({
    width: "100%",
    maxWidth: layoutMode === "single" ? "920px" : "780px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "14px",
    marginBottom: layoutMode === "single" ? "4px" : "26px",
    textAlign: "center" as const,
  }),
  emptyLauncherKicker: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    flexWrap: "wrap" as const,
  },
  emptyLauncherBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "7px",
    padding: "7px 12px",
    borderRadius: "999px",
    border: "1px solid color-mix(in srgb, var(--accent) 16%, var(--border-dim))",
    background: "color-mix(in srgb, var(--bg-card) 76%, transparent)",
    color: "var(--text-secondary)",
    fontSize: "12px",
    fontWeight: 600,
    boxShadow: "0 12px 30px rgba(15, 23, 42, 0.04)",
  },
  emptyLauncherMeta: {
    fontSize: "12.5px",
    color: "var(--text-muted)",
    letterSpacing: "0.01em",
  },
  emptyLauncherTitle: {
    margin: 0,
    fontSize: "34px",
    lineHeight: 1.04,
    letterSpacing: "-0.04em",
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  emptyLauncherSubtitle: {
    margin: 0,
    fontSize: "15px",
    color: "var(--text-secondary)",
    maxWidth: "700px",
    lineHeight: "1.72",
  },
  emptyComposerDialog: (layoutMode: "single" | "split") => ({
    width: "100%",
    maxWidth: layoutMode === "single" ? "920px" : "860px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "18px",
    justifyContent: "flex-start",
    padding: layoutMode === "single" ? "20px 24px 22px" : "18px",
    borderRadius: "28px",
    border: "1px solid color-mix(in srgb, var(--accent) 14%, var(--chat-glass-border))",
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--chat-surface-strong) 96%, transparent), color-mix(in srgb, var(--chat-surface) 82%, transparent))",
    boxShadow: "var(--chat-shadow)",
    backdropFilter: "blur(24px) saturate(1.16)",
    WebkitBackdropFilter: "blur(24px) saturate(1.16)",
    boxSizing: "border-box" as const,
  }),
  emptyComposerTopBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    flexWrap: "wrap" as const,
  },
  emptyComposerPromptHint: {
    fontSize: "12px",
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase" as const,
    color: "var(--text-hint)",
  },
  emptyComposerToolRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap" as const,
  },
  emptyTopToolBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    height: "34px",
    padding: "0 12px",
    borderRadius: "999px",
    border: "1px solid var(--border-dim)",
    background: "color-mix(in srgb, var(--bg-card) 74%, transparent)",
    color: "var(--text-secondary)",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  emptyComposerInputShell: () => ({
    borderRadius: "24px",
    border: "1px solid color-mix(in srgb, var(--accent) 12%, var(--chat-glass-border))",
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--bg-input) 86%, transparent), color-mix(in srgb, var(--bg-subtle) 60%, transparent))",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.2)",
    display: "flex",
    flexDirection: "column" as const,
  }),
  attachedImagesContainer: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "10px",
    width: "100%",
    padding: "2px 4px 0",
  },
  attachedImageWrapper: {
    position: "relative" as const,
    width: "64px",
    height: "64px",
    borderRadius: "10px",
    overflow: "hidden",
    border: "1px solid var(--border-medium)",
  },
  attachedImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover" as const,
  },
  removeImageBtn: {
    position: "absolute" as const,
    top: "4px",
    right: "4px",
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    background: "rgba(0,0,0,0.6)",
    color: "#fff",
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  emptyComposerTextarea: (layoutMode: "single" | "split") => ({
    width: "100%",
    minHeight: layoutMode === "single" ? "120px" : "80px",
    padding: layoutMode === "single" ? "18px 22px" : "16px 20px",
    border: "none",
    outline: "none",
    resize: "none" as const,
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: layoutMode === "single" ? "17px" : "19px",
    lineHeight: "1.7",
    fontFamily: "var(--font-ui)",
    boxSizing: "border-box" as const,
    flex: 1,
  }),
  emptyComposerActionRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "10px",
  },
  emptyComposerActionBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    minHeight: "38px",
    padding: "8px 13px",
    borderRadius: "999px",
    border: "1px solid color-mix(in srgb, var(--accent) 8%, var(--border-dim))",
    background: "color-mix(in srgb, var(--bg-card) 68%, transparent)",
    color: "var(--text-secondary)",
    fontSize: "12.5px",
    fontWeight: 600,
    cursor: "pointer",
  },
  emptyComposerActionIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "18px",
    height: "18px",
    color: "var(--text-primary)",
  },
  emptyComposerActionLabel: {
    whiteSpace: "nowrap" as const,
  },
  emptyComposerFooter: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "14px",
    paddingTop: "2px",
  },
  emptyComposerFootnote: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexWrap: "wrap" as const,
    color: "var(--text-muted)",
    fontSize: "12px",
    lineHeight: 1.6,
  },
  emptyComposerFootnoteDot: {
    width: "4px",
    height: "4px",
    borderRadius: "999px",
    background: "var(--text-hint)",
    flexShrink: 0,
  },
  emptyComposerBottomRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    flexWrap: "wrap" as const,
  },
  emptyComposerSecondaryRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexWrap: "wrap" as const,
  },
  emptyComposerPrimaryRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "10px",
    flexWrap: "wrap" as const,
  },
  emptySecondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 12px",
    borderRadius: "999px",
    border: "1px solid var(--border-dim)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  emptyComposerSendBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    height: "44px",
    padding: "0 18px",
    borderRadius: "999px",
    border: "none",
    background:
      "linear-gradient(135deg, var(--accent), color-mix(in srgb, var(--accent) 74%, white))",
    color: "#fff",
    fontSize: "13px",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 18px 28px -16px color-mix(in srgb, var(--accent) 60%, transparent)",
  },
  emptyComposerStopBtn: {
    background: "linear-gradient(135deg, #0f172a, #334155)",
    boxShadow: "0 18px 28px -16px rgba(15, 23, 42, 0.55)",
  },
  emptyComposerResumeBtn: {
    background: "linear-gradient(135deg, #0f766e, #14b8a6)",
    boxShadow: "0 18px 28px -16px rgba(13, 148, 136, 0.5)",
  },
  messageBubbleWrap: (isUser: boolean) => ({
    width: "100%",
    maxWidth: "980px",
    minWidth: 0,
    display: "flex",
    flexDirection: "row" as const,
    justifyContent: isUser ? ("flex-end" as const) : ("flex-start" as const),
    gap: "12px",
    alignItems: "flex-start",
    alignSelf: "center",
    marginBottom: "2px",
  }),
  messageAvatar: (isUser: boolean) => ({
    width: "32px",
    height: "32px",
    borderRadius: "11px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: isUser
      ? "linear-gradient(135deg, var(--accent), color-mix(in srgb, var(--accent) 72%, white))"
      : "linear-gradient(135deg, color-mix(in srgb, var(--bg-card) 92%, transparent), color-mix(in srgb, var(--bg-subtle) 84%, transparent))",
    border: "1px solid var(--border-dim)",
    boxShadow: isUser
      ? "0 8px 18px -8px color-mix(in srgb, var(--accent) 48%, transparent)"
      : "0 8px 18px -10px rgba(0,0,0,0.12)",
    flexShrink: 0,
    marginTop: "2px",
    overflow: "hidden",
  }),
  messageAvatarImage: {
    width: "100%",
    height: "100%",
    display: "block",
    objectFit: "cover" as const,
  },
  messageBubble: (isUser: boolean) => ({
    width: isUser ? "fit-content" : "100%",
    maxWidth: "100%",
    minWidth: 0,
    padding: isUser ? "12px 15px" : "15px 17px",
    borderRadius: isUser ? "20px 20px 7px 20px" : "18px 18px 18px 7px",
    background: isUser
      ? "linear-gradient(135deg, color-mix(in srgb, var(--accent) 88%, #052e22), color-mix(in srgb, var(--accent) 62%, var(--warning)))"
      : "linear-gradient(180deg, color-mix(in srgb, var(--chat-surface-strong) 96%, transparent), color-mix(in srgb, var(--chat-surface) 82%, transparent))",
    color: isUser ? "#06130e" : "var(--text-primary)",
    border: isUser
      ? "1px solid color-mix(in srgb, var(--accent) 42%, transparent)"
      : "1px solid color-mix(in srgb, var(--accent) 10%, var(--chat-glass-border))",
    boxShadow: isUser
      ? "0 16px 28px -18px color-mix(in srgb, var(--accent) 50%, transparent)"
      : "var(--chat-shadow-soft)",
    fontSize: "14px",
    lineHeight: "1.7",
    overflowWrap: "break-word" as const,
    wordBreak: "normal" as const,
    userSelect: "text" as const,
    WebkitUserSelect: "text" as const,
    overflow: "hidden",
  }),
  messageBubbleColumn: (isUser: boolean) => ({
    width: isUser ? "auto" : "min(780px, calc(100% - 48px))",
    maxWidth: isUser ? "min(86%, 780px)" : "min(780px, calc(100% - 48px))",
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    alignItems: isUser ? ("flex-end" as const) : ("flex-start" as const),
    gap: "5px",
  }),
  bubbleCopyButton: (isUser: boolean, status: "idle" | "copied" | "failed") => ({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    width: "fit-content",
    minHeight: "24px",
    padding: "3px 7px",
    borderRadius: "7px",
    border: "1px solid var(--border-dim)",
    background:
      status === "copied"
        ? "color-mix(in srgb, var(--success, #16a34a) 14%, var(--bg-card))"
        : status === "failed"
          ? "color-mix(in srgb, var(--danger, #dc2626) 12%, var(--bg-card))"
          : "color-mix(in srgb, var(--bg-card) 90%, transparent)",
    color:
      status === "copied"
        ? "var(--success, #16a34a)"
        : status === "failed"
          ? "var(--danger, #dc2626)"
          : isUser
            ? "color-mix(in srgb, var(--accent) 78%, var(--text-secondary))"
            : "var(--text-hint)",
    fontSize: "11px",
    fontWeight: 600,
    lineHeight: 1.2,
    cursor: "pointer",
    userSelect: "none" as const,
    WebkitUserSelect: "none" as const,
    opacity: status === "idle" ? 0.78 : 1,
  }),
  messageText: {
    whiteSpace: "pre-wrap" as const,
    userSelect: "text" as const,
    WebkitUserSelect: "text" as const,
    fontFamily: "var(--font-ui)",
  },
  userMessageText: {
    maxWidth: "100%",
    minWidth: 0,
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
    overflowWrap: "break-word" as const,
    fontSize: "14px",
    lineHeight: "1.72",
    userSelect: "text" as const,
    WebkitUserSelect: "text" as const,
    fontFamily: "var(--font-ui)",
  },
  userImageGallery: {
    display: "flex",
    flexWrap: "wrap" as const,
    justifyContent: "flex-end",
    gap: "8px",
    maxWidth: "min(100%, 520px)",
  },
  markdownBody: {
    maxWidth: "100%",
    minWidth: 0,
    fontSize: "14px",
    lineHeight: "1.72",
    userSelect: "text" as const,
    WebkitUserSelect: "text" as const,
    fontFamily: "var(--font-ui)",
  },
  assistantTurnStack: {
    width: "min(820px, calc(100% - 48px))",
    maxWidth: "min(820px, calc(100% - 48px))",
    display: "flex",
    flexDirection: "column" as const,
    gap: "12px",
    minWidth: 0,
  },
  assistantTurnSection: {
    width: "100%",
    minWidth: 0,
  },
  assistantReplyBubble: {
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--chat-surface-strong) 96%, transparent), color-mix(in srgb, var(--chat-surface) 82%, transparent))",
  },
  assistantUsageStats: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap" as const,
    width: "fit-content",
    maxWidth: "100%",
    padding: "4px 8px",
    borderRadius: "999px",
    border: "1px solid var(--border-dim)",
    background: "color-mix(in srgb, var(--chat-surface-strong) 82%, transparent)",
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
    fontSize: "10.5px",
    lineHeight: 1.4,
  },
  assistantPlaceholder: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    color: "var(--text-secondary)",
    fontSize: "13px",
    lineHeight: 1.6,
  },
  assistantPlaceholderDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: "var(--accent)",
    boxShadow: "0 0 0 4px color-mix(in srgb, var(--accent) 16%, transparent)",
    flexShrink: 0,
  },
  toolSummaryCard: {
    width: "100%",
    padding: "14px 16px",
    borderRadius: "22px 22px 22px 8px",
    border: "1px solid color-mix(in srgb, var(--warning, #d97706) 22%, var(--border-dim))",
    background:
      "linear-gradient(180deg, rgba(217,119,6,0.08), color-mix(in srgb, var(--bg-card) 94%, transparent))",
    boxShadow: "0 16px 32px rgba(15, 23, 42, 0.05)",
  },
  thinkingCard: {
    width: "100%",
    borderRadius: "18px 18px 18px 8px",
    border: "1px solid color-mix(in srgb, var(--warning, #d97706) 20%, var(--border-dim))",
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--warning, #d97706) 10%, var(--chat-surface-strong)), color-mix(in srgb, var(--chat-surface) 92%, transparent))",
    overflow: "hidden",
    boxShadow: "0 14px 28px rgba(15, 23, 42, 0.04)",
  },
  thinkingHeader: {
    width: "100%",
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 12px",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 700,
    textAlign: "left" as const,
  },
  thinkingBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 8px",
    borderRadius: 999,
    background: "color-mix(in srgb, var(--warning, #d97706) 14%, transparent)",
    color: "var(--warning, #d97706)",
    flexShrink: 0,
  },
  thinkingMeta: {
    flex: 1,
    minWidth: 0,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    fontSize: 11,
  },
  // ── Prior (superseded) assistant reply collapsible ──
  // Greyed-out, collapsed-by-default block for an earlier assistant reply that
  // a subsequent tool round overrode. Visually muted relative to the Thinking
  // card (which is amber) so the live/final reply stays the visual focus.
  priorTextCard: {
    width: "100%",
    borderRadius: "14px 14px 14px 7px",
    border: "1px solid var(--border-dim)",
    background: "color-mix(in srgb, var(--bg-subtle) 70%, transparent)",
    overflow: "hidden",
  },
  priorTextHeader: {
    width: "100%",
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 11px",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 700,
    textAlign: "left" as const,
  },
  priorTextBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 8px",
    borderRadius: 999,
    background: "color-mix(in srgb, var(--text-muted) 14%, transparent)",
    color: "var(--text-muted)",
    flexShrink: 0,
  },
  priorTextMeta: {
    flex: 1,
    minWidth: 0,
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
    fontSize: 11,
  },
  priorTextBody: {
    borderTop: "1px solid var(--border-dim)",
    padding: "10px 12px 12px",
    color: "var(--text-muted)",
    opacity: 0.85,
    fontSize: 13,
    lineHeight: 1.65,
    userSelect: "text" as const,
    WebkitUserSelect: "text" as const,
  },
  thinkingBody: {
    borderTop: "1px solid color-mix(in srgb, var(--warning, #d97706) 14%, var(--border-dim))",
    padding: "11px 13px 13px",
    color: "var(--text-secondary)",
    fontSize: 13,
    lineHeight: 1.65,
    userSelect: "text" as const,
    WebkitUserSelect: "text" as const,
  },
  toolSummaryHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap" as const,
    marginBottom: "10px",
  },
  toolSummaryBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 9px",
    borderRadius: "999px",
    background: "rgba(217,119,6,0.12)",
    color: "var(--warning, #d97706)",
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.02em",
  },
  toolSummaryName: {
    fontSize: "12px",
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  toolSummaryMode: {
    fontSize: "11px",
    color: "var(--text-secondary)",
  },
  inputArea: {
    display: "flex",
    alignItems: "flex-end",
    gap: "10px",
    width: "min(920px, calc(100% - 36px))",
    margin: "0 auto 16px",
    padding: "12px",
    borderRadius: 22,
    border: "1px solid color-mix(in srgb, var(--accent) 12%, var(--chat-glass-border))",
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--chat-surface-strong) 94%, transparent), color-mix(in srgb, var(--chat-surface) 82%, transparent))",
    flexShrink: 0,
    flexWrap: "wrap" as const,
    boxShadow: "var(--chat-shadow-soft)",
    backdropFilter: "blur(24px) saturate(1.16)",
    WebkitBackdropFilter: "blur(24px) saturate(1.16)",
  },
  inputTextarea: {
    flex: 1,
    minWidth: "min(420px, 100%)",
    minHeight: 48,
    padding: "12px 14px",
    fontSize: "14px",
    lineHeight: "1.6",
    background: "color-mix(in srgb, var(--bg-input) 70%, transparent)",
    border: "1px solid var(--chat-glass-border)",
    borderRadius: "16px",
    color: "var(--text-primary)",
    resize: "none" as const,
    outline: "none",
    fontFamily: "var(--font-ui)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.12)",
    transition: "border-color var(--motion-normal), box-shadow var(--motion-normal)",
  },
  sendBtn: {
    width: "44px",
    height: "44px",
    borderRadius: "16px",
    background:
      "linear-gradient(135deg, var(--accent), color-mix(in srgb, var(--accent) 74%, white))",
    color: "#fff",
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "opacity 0.2s, transform 0.1s",
    boxShadow: "0 18px 28px -16px color-mix(in srgb, var(--accent) 60%, transparent)",
  },
  voiceBtn: (active: boolean) => ({
    width: "44px",
    height: "44px",
    borderRadius: "14px",
    border: active
      ? "1px solid color-mix(in srgb, var(--danger) 38%, transparent)"
      : "1px solid var(--border-dim)",
    background: active
      ? "color-mix(in srgb, var(--danger) 14%, var(--bg-card))"
      : "color-mix(in srgb, var(--bg-card) 88%, transparent)",
    color: active ? "var(--danger)" : "var(--text-secondary)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
    boxShadow: active ? "0 12px 24px -18px var(--danger)" : "var(--shadow-xs)",
  }),
  voiceStatusCard: (isError: boolean) => ({
    margin: "0 18px 8px",
    padding: "10px 12px",
    borderRadius: "12px",
    border: isError
      ? "1px solid color-mix(in srgb, var(--danger) 30%, var(--border-dim))"
      : "1px solid color-mix(in srgb, var(--accent) 18%, var(--border-dim))",
    background: isError
      ? "color-mix(in srgb, var(--danger) 8%, var(--bg-card))"
      : "color-mix(in srgb, var(--accent) 7%, var(--bg-card))",
  }),
  voiceStatusHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "10px",
    marginBottom: "6px",
  },
  voiceStatusBadge: (active: boolean, isError: boolean) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    fontWeight: 700,
    color: isError ? "var(--danger)" : active ? "var(--accent)" : "var(--text-secondary)",
  }),
  voiceStatusDismissBtn: {
    border: "none",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: "12px",
    cursor: "pointer",
  },
  voiceStatusText: {
    fontSize: "13px",
    lineHeight: 1.6,
    color: "var(--text-primary)",
    whiteSpace: "pre-wrap" as const,
  },
  voiceStatusHint: {
    fontSize: "12px",
    color: "var(--text-hint)",
  },
  voiceStatusError: {
    fontSize: "12px",
    lineHeight: 1.5,
    color: "var(--danger)",
  },
  stopBtn: {
    background: "linear-gradient(135deg, #0f172a, #334155)",
    boxShadow: "0 18px 28px -16px rgba(15, 23, 42, 0.55)",
  },
  resumeBtn: {
    background: "linear-gradient(135deg, #0f766e, #14b8a6)",
    boxShadow: "0 18px 28px -16px rgba(13, 148, 136, 0.5)",
  },
  // ── Approval dialog styles ──
  approvalOverlay: {
    position: "absolute" as const,
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  approvalDialog: {
    width: "min(560px, calc(100% - 16px))",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: "16px",
    padding: "20px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
    boxShadow: "0 10px 40px rgba(0,0,0,0.2)",
  },
  approvalHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  approvalIcon: { fontSize: "18px", color: "var(--accent)" },
  approvalTitle: {
    fontSize: "14.5px",
    fontWeight: 600,
    color: "var(--text-primary)",
    flex: 1,
  },
  approvalAgentBadge: {
    fontSize: "11px",
    padding: "3px 8px",
    borderRadius: "999px",
    background: "color-mix(in srgb, var(--accent) 12%, transparent)",
    color: "var(--accent)",
    border: "1px solid color-mix(in srgb, var(--accent) 22%, transparent)",
    fontWeight: 700,
  },
  approvalBadge: {
    fontSize: "11px",
    padding: "3px 8px",
    borderRadius: "6px",
    background: "var(--bg-subtle)",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
    fontWeight: 500,
  },
  approvalHint: {
    fontSize: "12px",
    lineHeight: "1.6",
    color: "var(--text-secondary)",
  },
  approvalTextarea: {
    width: "100%",
    padding: "12px",
    fontSize: "13px",
    lineHeight: "1.6",
    background: "var(--bg-input)",
    border: "1px solid var(--border-medium)",
    borderRadius: "10px",
    color: "var(--text-primary)",
    resize: "vertical" as const,
    outline: "none",
    fontFamily: "var(--font-mono)",
    boxSizing: "border-box" as const,
    boxShadow: "0 2px 6px rgba(0,0,0,0.02) inset",
  },
  approvalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "4px",
  },
  approvalRejectBtn: {
    padding: "8px 18px",
    fontSize: "12.5px",
    background: "var(--bg-subtle)",
    border: "1px solid var(--border-medium)",
    borderRadius: "8px",
    color: "var(--text-secondary)",
    cursor: "pointer",
    fontWeight: 500,
  },
  approvalApproveBtn: {
    padding: "8px 18px",
    fontSize: "12.5px",
    background: "var(--accent)",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: 600,
    boxShadow: "0 2px 6px color-mix(in srgb, var(--accent) 40%, transparent)",
  },
};
