import type { FileIconSpec } from "./types";

const file = (
  key: string,
  badge: string,
  accent: string,
  accentSoft: string,
  glyph: FileIconSpec["glyph"],
  category: FileIconSpec["category"],
): FileIconSpec => ({
  key,
  kind: "file",
  badge,
  accent,
  accentSoft,
  glyph,
  category,
});

const folder = (
  key: string,
  badge: string,
  accent: string,
  accentSoft: string,
): FileIconSpec => ({
  key,
  kind: "folder",
  badge,
  accent,
  accentSoft,
  glyph: "badge",
  category: "folder",
});

const FILE_ICON_SPECS: Record<string, FileIconSpec> = {
  default: file("default", "TXT", "#64748B", "#CBD5E1", "lines", "document"),
  text: file("text", "TXT", "#475569", "#CBD5E1", "lines", "document"),
  markdown: file("markdown", "MD", "#2563EB", "#93C5FD", "markdown", "document"),
  typescript: file("typescript", "TS", "#2563EB", "#93C5FD", "badge", "code"),
  tsx: file("tsx", "TS", "#0EA5E9", "#67E8F9", "react", "code"),
  javascript: file("javascript", "JS", "#EAB308", "#FDE68A", "badge", "code"),
  jsx: file("jsx", "JS", "#06B6D4", "#67E8F9", "react", "code"),
  json: file("json", "{}", "#F59E0B", "#FCD34D", "json", "config"),
  yaml: file("yaml", "YML", "#EF4444", "#FCA5A5", "badge", "config"),
  toml: file("toml", "TOM", "#B45309", "#FBBF24", "badge", "config"),
  ini: file("ini", "INI", "#8B5CF6", "#C4B5FD", "gear", "config"),
  env: file("env", "ENV", "#475569", "#94A3B8", "gear", "config"),
  config: file("config", "CFG", "#7C3AED", "#C4B5FD", "gear", "config"),
  shell: file("shell", "SH", "#16A34A", "#86EFAC", "terminal", "code"),
  docker: file("docker", "DK", "#0284C7", "#7DD3FC", "package", "package"),
  make: file("make", "MK", "#0F766E", "#5EEAD4", "gear", "config"),
  python: file("python", "PY", "#2563EB", "#FCD34D", "badge", "code"),
  rust: file("rust", "RS", "#C2410C", "#FDBA74", "badge", "code"),
  go: file("go", "GO", "#0891B2", "#67E8F9", "badge", "code"),
  java: file("java", "JV", "#C2410C", "#FCA5A5", "badge", "code"),
  kotlin: file("kotlin", "KT", "#7C3AED", "#C4B5FD", "badge", "code"),
  swift: file("swift", "SW", "#EA580C", "#FDBA74", "badge", "code"),
  ruby: file("ruby", "RB", "#DC2626", "#FCA5A5", "badge", "code"),
  php: file("php", "PHP", "#4F46E5", "#C7D2FE", "badge", "code"),
  csharp: file("csharp", "C#", "#7C3AED", "#DDD6FE", "badge", "code"),
  cpp: file("cpp", "C+", "#2563EB", "#BFDBFE", "badge", "code"),
  c: file("c", "C", "#0F766E", "#99F6E4", "badge", "code"),
  lua: file("lua", "LUA", "#1D4ED8", "#93C5FD", "badge", "code"),
  r: file("r", "R", "#2563EB", "#BFDBFE", "badge", "code"),
  sql: file("sql", "SQL", "#0F766E", "#99F6E4", "database", "database"),
  graphql: file("graphql", "GQL", "#C026D3", "#F0ABFC", "globe", "code"),
  html: file("html", "HTML", "#EA580C", "#FDBA74", "globe", "document"),
  css: file("css", "CSS", "#2563EB", "#93C5FD", "badge", "document"),
  sass: file("sass", "SAS", "#DB2777", "#F9A8D4", "badge", "document"),
  vue: file("vue", "VUE", "#059669", "#6EE7B7", "vue", "code"),
  svelte: file("svelte", "SV", "#EA580C", "#FDBA74", "svelte", "code"),
  astro: file("astro", "AS", "#7C2D12", "#FDBA74", "astro", "code"),
  xml: file("xml", "XML", "#DC2626", "#FCA5A5", "badge", "document"),
  protobuf: file("protobuf", "PB", "#0F766E", "#5EEAD4", "badge", "code"),
  notebook: file("notebook", "NB", "#2563EB", "#C4B5FD", "table", "document"),
  storybook: file("storybook", "SB", "#DB2777", "#F9A8D4", "storybook", "document"),
  test: file("test", "T", "#16A34A", "#86EFAC", "test", "code"),
  package: file("package", "PKG", "#0F766E", "#5EEAD4", "package", "package"),
  git: file("git", "GIT", "#F97316", "#FDBA74", "git", "config"),
  lock: file("lock", "L", "#64748B", "#CBD5E1", "lock", "security"),
  key: file("key", "K", "#CA8A04", "#FDE68A", "key", "security"),
  certificate: file("certificate", "CRT", "#0F766E", "#99F6E4", "certificate", "security"),
  image: file("image", "IMG", "#059669", "#86EFAC", "image", "image"),
  svg: file("svg", "SVG", "#F97316", "#FDBA74", "image", "image"),
  video: file("video", "VID", "#DC2626", "#FCA5A5", "video", "video"),
  audio: file("audio", "AUD", "#7C3AED", "#DDD6FE", "audio", "audio"),
  archive: file("archive", "ZIP", "#B45309", "#FDE68A", "archive", "archive"),
  binary: file("binary", "BIN", "#334155", "#94A3B8", "wasm", "binary"),
  wasm: file("wasm", "WA", "#7C3AED", "#C4B5FD", "wasm", "binary"),
  font: file("font", "Aa", "#0284C7", "#BAE6FD", "font", "font"),
  pdf: file("pdf", "PDF", "#DC2626", "#FCA5A5", "badge", "document"),
  spreadsheet: file("spreadsheet", "XL", "#15803D", "#86EFAC", "table", "document"),
  database: file("database", "DB", "#0F766E", "#99F6E4", "database", "database"),
  log: file("log", "LOG", "#475569", "#CBD5E1", "lines", "document"),
  folder: folder("folder", "DIR", "#D97706", "#FCD34D"),
  "folder-src": folder("folder-src", "SRC", "#2563EB", "#93C5FD"),
  "folder-components": folder("folder-components", "UI", "#7C3AED", "#C4B5FD"),
  "folder-pages": folder("folder-pages", "PG", "#0F766E", "#5EEAD4"),
  "folder-hooks": folder("folder-hooks", "HK", "#06B6D4", "#67E8F9"),
  "folder-assets": folder("folder-assets", "AS", "#059669", "#6EE7B7"),
  "folder-styles": folder("folder-styles", "ST", "#DB2777", "#F9A8D4"),
  "folder-scripts": folder("folder-scripts", "SC", "#16A34A", "#86EFAC"),
  "folder-docs": folder("folder-docs", "DOC", "#2563EB", "#BFDBFE"),
  "folder-tests": folder("folder-tests", "T", "#16A34A", "#BBF7D0"),
  "folder-public": folder("folder-public", "WEB", "#0284C7", "#BAE6FD"),
  "folder-config": folder("folder-config", "CFG", "#7C3AED", "#DDD6FE"),
  "folder-github": folder("folder-github", "GH", "#334155", "#CBD5E1"),
  "folder-node": folder("folder-node", "N", "#15803D", "#86EFAC"),
  "folder-dist": folder("folder-dist", "OUT", "#EA580C", "#FDBA74"),
  "folder-build": folder("folder-build", "BLD", "#C2410C", "#FCA5A5"),
  "folder-git": folder("folder-git", "G", "#F97316", "#FDBA74"),
};

export function getFileIconSpec(iconKey: string): FileIconSpec {
  return FILE_ICON_SPECS[iconKey] ?? FILE_ICON_SPECS.default;
}
